version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db/library"

  backend:
    build: .
    container_name: backend_api
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db/library"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
